{{ config(materialized='incremental', unique_key=['hk_material', 'load_date']) }}

/*
    Satellite: Material Business Enrichment (HT-domain)
    Parent: hub_material
    Source: stg_sap__zmm_material_business

    Carries ONLY genuinely-HT-domain attributes — fields with no
    SAP-native home. Currently: lifecycle_months (HT's expected service
    life of the device, used in warranty/TCO analysis — not a standard
    SAP master-data field), primary_vendor_id (HT's preferred supplier
    LIFNR; soft FK to hub_vendor — SAP can list many sources via EORD
    but doesn't designate one as 'primary' in the business sense), and
    free-form notes.

    Phase β cleanup (2026-05-05) dropped avg_unit_cost_eur — actual unit
    costs live in sat_po_item.unit_price (PO line-item NETPR/EKPO) and
    standard prices live in MBEW.STPRS. Carrying a separate 'curated'
    cost on the Z-table created a third source of truth and was never
    consumed. equipment_category remains intentionally absent (derived
    in dim_material from material_group).

    Source convention: in production, this comes from a custom Z-table
    (ZMM_MATERIAL_BUSINESS or similar) populated by HT's material-
    management workflow. On synthetic demo data, generated by
    scripts/generate_sap_sample_data.py from the MATERIALS structure.

    Sparseness: production deployments will have many hub_material rows
    without a corresponding sat_material_business row. Consumers should
    LEFT JOIN.
*/

WITH src AS (
    SELECT
        hk_material,
        hashdiff_zmm_material_business AS hashdiff,
        LIFECYCLE_MONTHS AS lifecycle_months,
        PRIMARY_VENDOR_ID AS primary_vendor_id,
        NOTES AS notes,
        load_date,
        record_source
    FROM {{ ref('stg_sap__zmm_material_business') }}
)

SELECT * FROM src
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 FROM {{ this }} t
    WHERE t.hk_material = src.hk_material
      AND t.hashdiff = src.hashdiff
)
{% endif %}
