{{ config(materialized='incremental', unique_key=['hk_vendor', 'load_date']) }}

/*
    Satellite: Vendor Business Enrichment (HT-domain)
    Parent: hub_vendor
    Source: stg_sap__zmm_vendor_business

    Carries ONLY genuinely-HT-domain attributes — fields that have no
    SAP-native home. Currently: equipment_types (HT's CPE-category tags,
    semicolon-delimited), contract_status (HT's lifecycle classification),
    quality_rating (HT's internal A+/A/B/... scoring), and free-form notes.

    Phase β cleanup (2026-05-05) dropped lead_time_days — that lives in
    MARC.PLIFZ (planned delivery time per material/plant) and is exposed
    via sat_material_plant. Payment terms similarly live in LFB1.ZTERM
    via sat_vendor_commercial. The Z-table should NOT shadow SAP-native
    fields.

    Source convention: in production, this comes from a custom Z-table
    (ZMM_VENDOR_BUSINESS or similar) populated by HT's vendor-management
    workflow. On synthetic demo data, it's generated by
    scripts/generate_sap_sample_data.py from the VENDORS structure.

    Sparseness: production deployments will have many hub_vendor rows
    without a corresponding sat_vendor_business row (Z-table only covers
    curated vendors). Consumers should LEFT JOIN.
*/

WITH src AS (
    SELECT
        hk_vendor,
        hashdiff_zmm_vendor_business AS hashdiff,
        EQUIPMENT_TYPES AS equipment_types,
        CONTRACT_STATUS AS contract_status,
        QUALITY_RATING AS quality_rating,
        NOTES AS notes,
        load_date,
        record_source
    FROM {{ ref('stg_sap__zmm_vendor_business') }}
)

SELECT * FROM src
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 FROM {{ this }} t
    WHERE t.hk_vendor = src.hk_vendor
      AND t.hashdiff = src.hashdiff
)
{% endif %}
