"""Hotfix #65 — tests for scope re-derivation guard.

Validates that `_has_deployed_s2t_rows` correctly distinguishes
Stage A stub rows (target_model empty) from Piece 8 Deploy rows
(target_model populated), and that the guard sentinel path in
`confirm_scope` is reachable.

The full `confirm_scope` integration path (propose→revise→confirm)
is exercised by scripts/regression_piece8.py scenario 22 and not
duplicated here.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT / "scripts"))

import _scope_derivation as sd  # noqa: E402


_S2T_FIELDS = [
    "id", "business_term_id", "business_term_name", "source_table",
    "source_field", "source_description", "target_model", "target_column",
    "transformation_logic_plain", "transformation_logic_sql",
    "join_description", "filter_description", "notes",
    "transformation_logic_plain_business",
]


def _write_csv(path: Path, rows: list[dict]) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=_S2T_FIELDS, lineterminator="\n",
                           quoting=csv.QUOTE_MINIMAL)
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k, "") for k in _S2T_FIELDS})


def test_rewrite_s2t_for_term_proceeds_with_stage_a_stub_only(
    tmp_path, monkeypatch,
) -> None:
    """Happy path: only Stage A stub rows (target_model empty) → guard
    returns False, confirm_scope path would proceed."""
    tmp_csv = tmp_path / "s2t_mapping.csv"
    _write_csv(tmp_csv, [
        {"id": "S2T-0001", "business_term_id": "BG999",
         "source_table": "EKKO", "source_field": "EBELN",
         "notes": "stage_a_derived"},
        {"id": "S2T-0002", "business_term_id": "BG999",
         "source_table": "EKPO", "source_field": "MENGE",
         "notes": "stage_a_derived"},
    ])
    monkeypatch.setattr(sd, "_S2T_CSV", tmp_csv)

    has_deployed, count = sd._has_deployed_s2t_rows("BG999")
    assert has_deployed is False
    assert count == 0


def test_rewrite_s2t_for_term_blocks_with_deployed_rows(
    tmp_path, monkeypatch,
) -> None:
    """Blocked path: at least one row with target_model populated →
    guard returns True with count. confirm_scope would return
    ConfirmationResult(success=False, error=<...>).

    CSV file on disk must NOT be modified by the check itself."""
    tmp_csv = tmp_path / "s2t_mapping.csv"
    original_rows = [
        {"id": "S2T-0010", "business_term_id": "BG888",
         "source_table": "EKKO", "source_field": "EBELN",
         "target_model": "fact_purchase_orders",
         "target_column": "purchase_order_number",
         "notes": "Generated by Claude create_s2t_with_implementation"},
        {"id": "S2T-0011", "business_term_id": "BG888",
         "source_table": "EKKO", "source_field": "LIFNR",
         "target_model": "",  # mixed: this one is stub
         "notes": "stage_a_derived"},
    ]
    _write_csv(tmp_csv, original_rows)
    monkeypatch.setattr(sd, "_S2T_CSV", tmp_csv)

    # Snapshot file bytes before guard check
    bytes_before = tmp_csv.read_bytes()

    has_deployed, count = sd._has_deployed_s2t_rows("BG888")
    assert has_deployed is True
    assert count == 1, f"expected 1 deployed row, got {count}"

    # Guard is read-only — CSV must be byte-identical after check
    bytes_after = tmp_csv.read_bytes()
    assert bytes_before == bytes_after, "guard mutated s2t_mapping.csv"


def test_rewrite_s2t_for_term_unknown_term_is_false(
    tmp_path, monkeypatch,
) -> None:
    """Defense-in-depth: term_id not in CSV → no false blocks."""
    tmp_csv = tmp_path / "s2t_mapping.csv"
    _write_csv(tmp_csv, [
        {"id": "S2T-0001", "business_term_id": "BG111",
         "source_table": "EKKO", "source_field": "EBELN",
         "target_model": "fact_purchase_orders"},
    ])
    monkeypatch.setattr(sd, "_S2T_CSV", tmp_csv)

    has_deployed, count = sd._has_deployed_s2t_rows("BG999_does_not_exist")
    assert has_deployed is False
    assert count == 0


# ─── KI-105: confirm_scope in-process parquet sync (full flow) ─────

import json as _json  # noqa: E402
import duckdb  # noqa: E402


_BG_FIELDS = [
    "id", "term_name", "display_name", "definition", "unit", "grain",
    "owner", "approved_by", "status", "domain", "related_terms", "notes",
    "created_date", "business_join_description", "business_filter_description",
    "archive_id", "archived_at_utc", "archived_reason_code",
    "archived_reason_text", "scope_derivation_history_json",
]


def _make_propose_history(tables: list[str]) -> dict:
    return {"iterations": [{
        "iter_num": 1, "mode": "propose",
        "timestamp": "2026-01-01T00:00:00", "analyst_instruction": None,
        "llm_response": {
            "proposed_tables": tables,
            "primary_field_per_table": {t: "X" for t in tables},
            "rationale_per_table": {t: f"r-{t}" for t in tables},
            "join_path": [], "blockers": [],
            "attestation_echo": {}, "confidence": "high",
            "confidence_rationale": "t",
            "diff_from_prior": None, "reasoning_for_diff": None,
        },
        "validation_issues": [], "analyst_action": None, "usage": {},
    }]}


def _setup_confirm_scope_fixture(
    tmp_path: Path, monkeypatch, tables: list[str],
) -> tuple[Path, Path, Path]:
    """Build a confirm_scope-ready skeleton: dbt/seeds + data/parquet
    dirs, cpe_analytics.duckdb with raw_sap.<tables>, BG999 row in
    business_glossary.csv with a propose iteration, empty s2t_mapping.
    Patches sd's module paths to point at tmp_path."""
    (tmp_path / "dbt" / "seeds").mkdir(parents=True)
    (tmp_path / "data" / "parquet" / "main_seeds").mkdir(parents=True)

    db_path = tmp_path / "cpe_analytics.duckdb"
    conn = duckdb.connect(str(db_path))
    conn.execute("CREATE SCHEMA raw_sap")
    for t in tables:
        conn.execute(f'CREATE TABLE raw_sap."{t}" (placeholder INTEGER)')
    conn.close()

    bg_csv = tmp_path / "dbt" / "seeds" / "business_glossary.csv"
    bg_row = [
        "BG999", "test_term", "Test Term", "test def", "count", "month",
        "Owner", "Approver", "draft", "procurement", "", "", "2026-01-01",
        "", "", "", "", "", "",
        _json.dumps(_make_propose_history(tables)),
    ]
    with bg_csv.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f, lineterminator="\n", quoting=csv.QUOTE_MINIMAL)
        w.writerow(_BG_FIELDS)
        w.writerow(bg_row)

    s2t_csv = tmp_path / "dbt" / "seeds" / "s2t_mapping.csv"
    _write_csv(s2t_csv, [])

    monkeypatch.setattr(sd, "_ROOT", tmp_path)
    monkeypatch.setattr(sd, "_DB", db_path)
    monkeypatch.setattr(sd, "_BG_CSV", bg_csv)
    monkeypatch.setattr(sd, "_S2T_CSV", s2t_csv)
    return bg_csv, s2t_csv, tmp_path


def test_confirm_scope_inprocess_writes_parquet_correctly(
    tmp_path, monkeypatch,
) -> None:
    """Happy path: confirm_scope's in-process sync writes a parquet
    where the term has status=scope_confirmed (KI-105 fix)."""
    bg_csv, s2t_csv, project_root = _setup_confirm_scope_fixture(
        tmp_path, monkeypatch, ["mseg"],
    )

    result = sd.confirm_scope("BG999", 1, "test_user")

    assert result.success is True, (
        f"expected success; got error={result.error!r}"
    )
    pq = (project_root / "data" / "parquet" / "main_seeds"
          / "business_glossary.parquet")
    assert pq.exists(), "business_glossary.parquet was not written"
    c = duckdb.connect(":memory:")
    try:
        row = c.execute(
            f"SELECT status FROM '{pq.as_posix()}' WHERE id='BG999'"
        ).fetchone()
        assert row is not None and row[0] == "scope_confirmed", (
            f"expected scope_confirmed in parquet; got {row}"
        )
    finally:
        c.close()


def test_confirm_scope_strict_rollback_on_seed_write_failure(
    tmp_path, monkeypatch,
) -> None:
    """Strict semantics: any sync warning rolls back both CSVs and
    returns success=False with the warning text in error (KI-105)."""
    bg_csv, s2t_csv, _ = _setup_confirm_scope_fixture(
        tmp_path, monkeypatch, ["mseg"],
    )
    bg_original = bg_csv.read_bytes()
    s2t_original = s2t_csv.read_bytes()

    # Inject a warning. Patch on the _parquet_sync module so
    # confirm_scope's local `from … import …` picks up the fake.
    import _parquet_sync

    def _fake_sync(**kwargs):
        return f"injected failure for {kwargs.get('seed_name')}"

    monkeypatch.setattr(
        _parquet_sync, "sync_parquet_and_invalidate", _fake_sync,
    )

    result = sd.confirm_scope("BG999", 1, "test_user")

    assert result.success is False
    assert "injected failure" in (result.error or "")
    assert bg_csv.read_bytes() == bg_original, (
        "business_glossary.csv was not restored after rollback"
    )
    assert s2t_csv.read_bytes() == s2t_original, (
        "s2t_mapping.csv was not restored after rollback"
    )


def test_confirm_scope_skip_parquet_export_when_flag_false(
    tmp_path, monkeypatch,
) -> None:
    """export_parquet=False: CSV writes still happen, parquet skipped,
    success=True (used by regression harnesses that restore state)."""
    bg_csv, s2t_csv, project_root = _setup_confirm_scope_fixture(
        tmp_path, monkeypatch, ["mseg"],
    )
    pq = (project_root / "data" / "parquet" / "main_seeds"
          / "business_glossary.parquet")
    assert not pq.exists()

    result = sd.confirm_scope(
        "BG999", 1, "test_user", export_parquet=False,
    )

    assert result.success is True, (
        f"expected success; got error={result.error!r}"
    )
    assert not pq.exists(), "skip flag not honored — parquet was written"
    with bg_csv.open() as f:
        bg999 = next(r for r in csv.DictReader(f) if r["id"] == "BG999")
    assert bg999["status"] == "scope_confirmed"


# ─── harness ───────────────────────────────────────────────────────

def _run_standalone() -> int:
    import tempfile
    import shutil as _shutil

    class _MP:
        def __init__(self): self.saved = []
        def setattr(self, obj, name, val):
            self.saved.append((obj, name, getattr(obj, name)))
            setattr(obj, name, val)
        def restore(self):
            for obj, name, val in reversed(self.saved):
                setattr(obj, name, val)

    tests = [
        test_rewrite_s2t_for_term_proceeds_with_stage_a_stub_only,
        test_rewrite_s2t_for_term_blocks_with_deployed_rows,
        test_rewrite_s2t_for_term_unknown_term_is_false,
        test_confirm_scope_inprocess_writes_parquet_correctly,
        test_confirm_scope_strict_rollback_on_seed_write_failure,
        test_confirm_scope_skip_parquet_export_when_flag_false,
    ]
    failed = 0
    for t in tests:
        tmpdir = Path(tempfile.mkdtemp())
        mp = _MP()
        try:
            t(tmpdir, mp)
            print(f"  [PASS] {t.__name__}")
        except AssertionError as e:
            failed += 1
            print(f"  [FAIL] {t.__name__}: {e}")
        except Exception as e:  # noqa: BLE001
            failed += 1
            print(f"  [ERR ] {t.__name__}: {type(e).__name__}: {e}")
        finally:
            mp.restore()
            _shutil.rmtree(tmpdir, ignore_errors=True)
    print(f"\n{len(tests) - failed}/{len(tests)} passed")
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(_run_standalone())
