-- DQ Rule: Total Goods Receipts by Month cannot be larger then 1 000 000
-- Business Term: Total Goods Receipts by Month (BG029)
-- Target: fact_goods_receipts_monthly.receipt_line_count
-- Severity: error
-- Generated by Claude API

-- This test cannot be implemented as specified
-- The target model fact_goods_receipts_monthly does not contain lead_time columns
-- Available columns: receipt_month, receipt_line_count, distinct_documents, distinct_vendors, distinct_materials
SELECT 'ERROR: lead_time column not found in target model' as error_message
WHERE 1=0
