-- DQ Rule: lead time cannot be negative
-- Business Term: Average Vendor Lead Time (BG001)
-- Target: fact_purchase_orders.po_date
-- Severity: error
-- Generated by Claude API

-- violating rows only
SELECT purchase_order_number, po_item_number, lead_time_days
FROM {{ ref('fact_purchase_orders') }}
WHERE lead_time_days IS NOT NULL AND lead_time_days < 0
