-- DQ Rule: total goods receipt per month cannot pass 1000000
-- Business Term: Total Goods Receipts by Month (BG029)
-- Target: fact_goods_receipts_monthly.receipt_line_count
-- Severity: error
-- Generated by Claude API

-- violating rows only
SELECT receipt_month, receipt_line_count
FROM {{ ref('fact_goods_receipts_monthly') }}
WHERE receipt_line_count IS NOT NULL AND receipt_line_count > 1000000
