-- DQ Rule: every vendor must have at least one PO  per quarter
-- Business Term: Average Vendor Lead Time (BG001)
-- Target: fact_purchase_orders.po_date
-- Severity: error
-- Generated by Claude API

-- Find vendors with quarters having no POs
WITH quarterly_po_counts AS (
  SELECT 
    vendor_id,
    DATE_TRUNC('quarter', po_date) AS quarter,
    COUNT(*) AS po_count
  FROM {{ ref('fact_purchase_orders') }}
  WHERE po_date IS NOT NULL
  GROUP BY vendor_id, DATE_TRUNC('quarter', po_date)
),
all_vendor_quarters AS (
  SELECT DISTINCT
    v.vendor_id,
    q.quarter
  FROM (SELECT DISTINCT vendor_id FROM {{ ref('fact_purchase_orders') }} WHERE vendor_id IS NOT NULL) v
  CROSS JOIN (SELECT DISTINCT DATE_TRUNC('quarter', po_date) AS quarter FROM {{ ref('fact_purchase_orders') }} WHERE po_date IS NOT NULL) q
)
SELECT 
  avq.vendor_id,
  avq.quarter
FROM all_vendor_quarters avq
LEFT JOIN quarterly_po_counts qpc ON avq.vendor_id = qpc.vendor_id AND avq.quarter = qpc.quarter
WHERE qpc.po_count IS NULL
