{{ config(severity='warn') }}
-- DQ Rule: No PO value should exceed 50000
-- Business Term: Average Vendor Lead Time (BG001)
-- Target: fact_purchase_orders.po_date
-- Severity: warn — advisory. The synthetic demo data intentionally contains some
--   rule violations so the governance layer has something to surface; this is a
--   data-quality monitor, not a build invariant.
-- Generated by Claude API

-- violating rows only
SELECT purchase_order_number, po_item_number, total_po_value
FROM {{ ref('fact_purchase_orders') }}
WHERE total_po_value IS NOT NULL AND total_po_value > 50000
