"""Wiki Pages — auto-generated knowledge documentation browser.

Reads .md files from the knowledge/ directory tree and presents them
as a browsable wiki with category tabs, page list, and styled content.
All content is auto-generated by scripts/build_knowledge_wiki.py from
dbt seeds — not hand-edited.
"""
from datetime import datetime
from pathlib import Path

import streamlit as st

WIKI_DIR = Path(__file__).resolve().parent.parent.parent / "knowledge"

CATEGORIES = [
    ("overview", "📖 Overview", ""),
    ("business_glossary", "📋 Business Glossary", "business_glossary"),
    ("sap_tables", "📦 SAP Tables", "sap_tables"),
    ("data_vault", "🏛️ Data Vault", "data_vault"),
    ("data_products", "📊 Data Products", "data_products"),
    ("domain", "🏢 Domain", "domain"),
    ("infrastructure", "🔧 Infrastructure", "infrastructure"),
    ("abap", "⚙️ ABAP", "abap"),
]

# Wiki content CSS — polished dark-theme styling
st.markdown("""
<style>
    .wiki-meta {
        font-size: 11px; color: #6b7280; padding: 4px 0 12px 0;
        border-bottom: 1px solid #1e2a45; margin-bottom: 16px;
    }
    .wiki-content h1 {
        font-size: 22px !important; color: #e0e0e0;
        border-bottom: 2px solid #3b82f6; padding-bottom: 6px; margin-top: 24px;
    }
    .wiki-content h2 {
        font-size: 18px !important; color: #d1d5db;
        border-bottom: 1px solid #1e2a45; padding-bottom: 4px; margin-top: 20px;
    }
    .wiki-content h3 {
        font-size: 15px !important; color: #9ca3af;
        border-left: 3px solid #3b82f6; padding-left: 8px; margin-top: 16px;
    }
    .wiki-content table {
        width: 100%; border-collapse: collapse; margin: 12px 0;
    }
    .wiki-content th {
        background-color: #131a2e; color: #93c5fd; text-align: left;
        padding: 6px 10px; border: 1px solid #1e2a45; font-size: 12px;
    }
    .wiki-content td {
        padding: 5px 10px; border: 1px solid #1e2a45; font-size: 12px; color: #d1d5db;
    }
    .wiki-content tr:nth-child(even) td { background-color: #0d1220; }
    .wiki-content tr:nth-child(odd) td { background-color: #0a0e17; }
    .wiki-content blockquote {
        border-left: 3px solid #fbbf24; background-color: #131a2e;
        padding: 8px 14px; margin: 12px 0; border-radius: 0 6px 6px 0;
        color: #d1d5db; font-size: 13px;
    }
    .wiki-content code {
        background-color: #1e2a45; padding: 1px 5px; border-radius: 3px;
        font-size: 12px; color: #93c5fd;
    }
    .wiki-content pre {
        background-color: #131a2e; border: 1px solid #1e2a45;
        border-radius: 6px; padding: 12px; overflow-x: auto;
    }
    .wiki-content pre code { background: none; padding: 0; color: #d1d5db; }
    .wiki-content p { line-height: 1.7; margin: 8px 0; }
    .wiki-content ul, .wiki-content ol { padding-left: 20px; }
    .wiki-content li { margin: 4px 0; line-height: 1.6; }
    .wiki-content a { color: #60a5fa; text-decoration: none; }
    .wiki-content a:hover { text-decoration: underline; }
    .wiki-page-btn {
        display: block; width: 100%; text-align: left;
        padding: 6px 10px; margin: 2px 0; border-radius: 4px;
        font-size: 13px; color: #d1d5db; cursor: pointer;
        border: none; background: transparent;
    }
    .wiki-page-btn:hover { background-color: #1e2a45; }
    .wiki-page-active {
        background-color: #1e2a45 !important; color: #93c5fd !important;
        border-left: 3px solid #3b82f6;
    }
</style>
""", unsafe_allow_html=True)

st.title("📖 Wiki Pages")
st.caption("Auto-generated knowledge documentation from dbt seeds")


def _clean_page_name(filename: str) -> str:
    """Convert filename to display name."""
    name = filename.replace(".md", "").replace("_", " ")
    # Special cases for SAP tables (keep uppercase)
    if name.upper() == name and len(name) <= 6:
        return name.upper()
    return name.title()


@st.cache_data(ttl=300)
def _load_page(path_str: str) -> str:
    return Path(path_str).read_text(encoding="utf-8")


@st.cache_data(ttl=300)
def _list_pages(folder_str: str) -> list:
    folder = Path(folder_str)
    if not folder.exists():
        return []
    return sorted(
        [f.name for f in folder.glob("*.md") if f.is_file()],
        key=lambda n: n.lower(),
    )


def _get_file_mtime(path: Path) -> str:
    try:
        ts = path.stat().st_mtime
        return datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M")
    except Exception:
        return "unknown"


if not WIKI_DIR.exists():
    st.warning(
        "Knowledge wiki not found. Run `python scripts/build_knowledge_wiki.py` "
        "to generate documentation."
    )
    st.stop()

# Build tab labels with page counts
tab_labels = []
for cat_key, cat_label, cat_folder in CATEGORIES:
    if cat_key == "overview":
        count = 1 if (WIKI_DIR / "index.md").exists() else 0
    else:
        folder = WIKI_DIR / cat_folder
        count = len(list(folder.glob("*.md"))) if folder.exists() else 0
    tab_labels.append(f"{cat_label} ({count})" if count else cat_label)

tabs = st.tabs(tab_labels)

for i, (cat_key, cat_label, cat_folder) in enumerate(CATEGORIES):
    with tabs[i]:
        if cat_key == "overview":
            # Overview tab — show index.md directly
            index_path = WIKI_DIR / "index.md"
            if index_path.exists():
                content = _load_page(str(index_path))
                mtime = _get_file_mtime(index_path)
                st.markdown(
                    f'<div class="wiki-meta">Last generated: {mtime} · '
                    f'Source: dbt/seeds/ · Category: overview</div>',
                    unsafe_allow_html=True,
                )
                st.markdown(
                    f'<div class="wiki-content">{content}</div>',
                    unsafe_allow_html=True,
                )
                # Also show top-level .md files (anti_patterns, knowledge_rules, etc.)
                top_level = sorted([
                    f.name for f in WIKI_DIR.glob("*.md")
                    if f.is_file() and f.name != "index.md"
                ])
                if top_level:
                    st.divider()
                    st.markdown("**Other top-level pages:**")
                    for page_name in top_level:
                        clean = _clean_page_name(page_name)
                        if st.button(clean, key=f"overview_{page_name}"):
                            page_path = WIKI_DIR / page_name
                            page_content = _load_page(str(page_path))
                            st.markdown(
                                f'<div class="wiki-meta">Last generated: '
                                f'{_get_file_mtime(page_path)} · '
                                f'Source: dbt/seeds/</div>',
                                unsafe_allow_html=True,
                            )
                            st.markdown(
                                f'<div class="wiki-content">{page_content}</div>',
                                unsafe_allow_html=True,
                            )
            else:
                st.info("No index.md found. Run `python scripts/build_knowledge_wiki.py`.")
        else:
            # Category tab — left panel (page list) + right panel (content)
            folder = WIKI_DIR / cat_folder
            pages = _list_pages(str(folder))

            if not pages:
                st.info(
                    f"No pages generated yet for {cat_label}. "
                    "Run `python scripts/build_knowledge_wiki.py`."
                )
                continue

            col_left, col_right = st.columns([1, 3])

            with col_left:
                # Search filter
                search = st.text_input(
                    "Filter pages",
                    key=f"wiki_search_{cat_key}",
                    placeholder="Search...",
                )
                filtered = [
                    p for p in pages
                    if not search or search.lower() in p.lower()
                    or search.lower() in _clean_page_name(p).lower()
                ]

                # Page list
                state_key = f"wiki_sel_{cat_key}"
                if state_key not in st.session_state and filtered:
                    st.session_state[state_key] = filtered[0]

                for page_name in filtered:
                    clean = _clean_page_name(page_name)
                    is_selected = st.session_state.get(state_key) == page_name
                    if st.button(
                        clean,
                        key=f"wiki_{cat_key}_{page_name}",
                        type="primary" if is_selected else "secondary",
                        use_container_width=True,
                    ):
                        st.session_state[state_key] = page_name

            with col_right:
                selected = st.session_state.get(state_key, filtered[0] if filtered else None)
                if selected:
                    page_path = folder / selected
                    if page_path.exists():
                        content = _load_page(str(page_path))
                        mtime = _get_file_mtime(page_path)
                        st.markdown(
                            f'<div class="wiki-meta">Last generated: {mtime} · '
                            f'Source: dbt/seeds/ · Category: {cat_folder}</div>',
                            unsafe_allow_html=True,
                        )
                        st.markdown(
                            f'<div class="wiki-content">\n\n{content}\n\n</div>',
                            unsafe_allow_html=True,
                        )
                    else:
                        st.warning(f"Page not found: {selected}")
