"""Direction F.3 — post-generation S2T SQL validator.

Architectural enforcement layer for cardinality safety: parses the SQL
generated by `create_s2t_with_implementation`, extracts JOIN clauses,
looks up the corresponding `join_cardinality` DARs, and refuses output
that uses a `catastrophic_fanout` join key. Refusal returns a structured
rejection that the caller surfaces via the existing `{"error": ...}`
channel.

Lazy on-demand analysis (closes known_issue #92): when no cardinality
DAR exists for a join's pair, invoke `run_join_cardinality_analysis
.analyze_pair` programmatically, refresh the in-DB table from the CSV,
and re-look up. If still no DAR (e.g., the analyzer found no candidates
or the pair lacks shared columns), the join passes through — no
evidence to gate on.

This is the SQL-output analog of Direction D §6.5's scope-proposal
hard-gate. Together they make the catastrophic-cartesian failure mode
unreachable through either LLM call regardless of LLM compliance.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Optional

import duckdb
import sqlglot
from sqlglot import expressions as exp

_SCRIPTS_DIR = Path(__file__).resolve().parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

_REF_PATTERN = re.compile(r"\{\{\s*ref\(['\"]([^'\"]+)['\"]\)\s*\}\}")
_STG_PREFIX = "stg_sap__"
_DAR_CSV = _SCRIPTS_DIR.parent / "dbt" / "seeds" / "domain_analysis_results.csv"


# ─── SQL parsing ──────────────────────────────────────────────────────

def _strip_jinja_refs(sql: str) -> str:
    """Replace `{{ ref('x') }}` with the bare table name `x` so sqlglot
    can parse without a dbt template engine.
    """
    return _REF_PATTERN.sub(r"\1", sql)


def _staging_to_raw(table_name: str) -> str:
    """Map `stg_sap__equi` -> `equi` (raw_sap table name).

    Tables that don't follow the staging convention are passed through
    in lowercase. Cardinality DARs key on raw_sap names, so this mapping
    is the join point.
    """
    if table_name.startswith(_STG_PREFIX):
        return table_name[len(_STG_PREFIX):].lower()
    return table_name.lower()


def _walk_eqs(expr) -> list:
    """Collect EQ nodes from an AND-tree of EQ comparisons."""
    out: list = []
    if isinstance(expr, exp.And):
        out.extend(_walk_eqs(expr.this))
        out.extend(_walk_eqs(expr.expression))
    elif isinstance(expr, exp.EQ):
        out.append(expr)
    return out


def _column_info(node):
    """Return (column_name, table_alias) from a Column expr; (None, None) otherwise."""
    if isinstance(node, exp.Column):
        return node.name, (node.table or None)
    return None, None


def _flatten_ctes(parsed: exp.Expression) -> exp.Expression:
    """Direction F.5 — inline CTE references as Subqueries so joins
    against CTE names can be resolved against base tables.

    For each `WITH x AS (...) ... JOIN x ...`, the outer `Table(name='x')`
    node is rewritten to `Subquery(this=<x's body>)` with the original
    alias preserved. CTE bodies are recursively expanded first so
    nested CTEs (a → b → ekbe) resolve fully. Aggregate-aware semantics
    intentionally not handled (F.5 spec defers to a future F.6).
    """
    if not isinstance(parsed, exp.Expression):
        return parsed

    cte_map: dict[str, exp.Expression] = {}
    for cte in parsed.find_all(exp.CTE):
        cte_map[cte.alias_or_name.lower()] = cte.this

    if not cte_map:
        return parsed

    def _expand(node):
        if isinstance(node, exp.Table) and node.name.lower() in cte_map:
            body = cte_map[node.name.lower()].copy()
            body = body.transform(_expand)
            sub = exp.Subquery(this=body)
            # Preserve column-resolution: if the CTE reference has an
            # explicit alias (`JOIN x AS xa`), use it; otherwise the
            # CTE's name itself is the alias used in column refs
            # (`JOIN x ON x.col = ...`).
            outer_alias = node.args.get("alias")
            if outer_alias:
                sub.set("alias", outer_alias)
            else:
                sub.set("alias", exp.TableAlias(
                    this=exp.Identifier(this=node.name, quoted=False)
                ))
            return sub
        return node

    return parsed.transform(_expand)


def _resolve_join_side(node) -> tuple[Optional[str], Optional[str]]:
    """Return (raw_table_name, alias) for a Join's left/right side node.

    - `Table` → straightforward staging-to-raw mapping.
    - `Subquery` (typically introduced by CTE inlining) → leftmost base
      `Table` inside the subquery acts as the effective base; the
      subquery's outer alias is preserved so column refs in the outer
      join's ON clause still resolve. This is F.5's minimal column-
      lineage proxy — works for `SELECT * FROM <base> ...` and
      `SELECT <cols> FROM <base> ...` patterns; aggregates pass through
      with semantically-imprecise but structurally-correct base mapping.
    """
    if isinstance(node, exp.Table):
        return _staging_to_raw(node.name), (node.alias or node.name).lower()
    if isinstance(node, exp.Subquery):
        outer_alias = node.alias.lower() if node.alias else None
        for tbl in node.find_all(exp.Table):
            return _staging_to_raw(tbl.name), outer_alias
    return None, None


def extract_joins_from_sql(sql: str) -> list[dict]:
    """Parse SQL (DuckDB dialect, dbt {{ ref() }} refs pre-stripped),
    return one dict per JOIN clause:

        {"left_table":  "<raw_sap_name>",
         "right_table": "<raw_sap_name>",
         "left_alias":  "<sql alias or table name>",
         "right_alias": "<sql alias or table name>",
         "kind":        "INNER" / "LEFT" / "RIGHT" / "FULL" / "CROSS",
         "join_keys":   [(left_col, right_col), ...]}

    Direction F.5 — CTEs are flattened (inlined as Subqueries) before
    join walking, so joins against CTE names resolve to the underlying
    base table. Joins inside CTE bodies are still walked (find_all is
    AST-wide). Output is deduped by (left_table, right_table, sorted
    keys) to handle the case where flattening produces structurally
    duplicate joins along multiple expansion paths.

    Joins whose ON clause cannot be cleanly parsed into equality pairs
    are dropped (validator passes them through — no evidence to gate on).
    """
    cleaned = _strip_jinja_refs(sql or "")
    if not cleaned.strip():
        return []
    try:
        statements = sqlglot.parse(cleaned, dialect="duckdb")
    except Exception:  # noqa: BLE001
        return []

    out: list[dict] = []
    seen: set[tuple] = set()
    for parsed in statements:
        if parsed is None:
            continue

        # F.5: flatten CTE references first.
        flat = _flatten_ctes(parsed)

        # Build alias-to-raw-table-name across the flattened statement.
        # Tables AND aliased Subqueries (CTEs after inlining) both
        # contribute to the alias map; the Subquery's effective base is
        # its leftmost FROM Table.
        alias_to_table: dict[str, str] = {}
        for tbl in flat.find_all(exp.Table):
            alias_to_table[(tbl.alias or tbl.name).lower()] = (
                _staging_to_raw(tbl.name)
            )
        for sub in flat.find_all(exp.Subquery):
            if not sub.alias:
                continue
            base_table = next(iter(sub.find_all(exp.Table)), None)
            if base_table is None:
                continue
            alias_to_table[sub.alias.lower()] = _staging_to_raw(base_table.name)

        for join in flat.find_all(exp.Join):
            right_tbl = join.this
            right_table, right_alias = _resolve_join_side(right_tbl)
            if right_table is None or right_alias is None:
                continue

            on = join.args.get("on")
            if on is None:
                continue

            keys: list[tuple[str, str]] = []
            left_aliases: set[str] = set()
            for eq in _walk_eqs(on):
                l_col, l_tbl = _column_info(eq.this)
                r_col, r_tbl = _column_info(eq.expression)
                if not (l_col and r_col and l_tbl and r_tbl):
                    continue
                lt = l_tbl.lower()
                rt = r_tbl.lower()
                if rt == right_alias:
                    keys.append((l_col, r_col))
                    left_aliases.add(lt)
                elif lt == right_alias:
                    keys.append((r_col, l_col))
                    left_aliases.add(rt)

            if not keys or len(left_aliases) != 1:
                continue
            left_alias = next(iter(left_aliases))
            left_table = alias_to_table.get(left_alias, left_alias)

            # Dedup key — sorted keys so reordering doesn't produce dupes.
            dedup_key = (
                left_table, right_table,
                tuple(sorted([k[0].upper() for k in keys])),
                tuple(sorted([k[1].upper() for k in keys])),
            )
            if dedup_key in seen:
                continue
            seen.add(dedup_key)

            out.append({
                "left_table": left_table,
                "right_table": right_table,
                "left_alias": left_alias,
                "right_alias": right_alias,
                "kind": str(join.args.get("kind") or "INNER").upper(),
                "join_keys": keys,
            })
    return out


# ─── Cardinality DAR lookup ──────────────────────────────────────────

def _query_pair_dars(conn, t1: str, t2: str) -> list[tuple[str, str]]:
    """Fetch (id, result_json) for non-superseded join_cardinality DARs
    whose source_tables list contains both t1 AND t2.

    F10-aware lookup using `list_contains(string_split(...))`.
    """
    pair_lex = sorted([t1.lower(), t2.lower()])
    try:
        return conn.execute(
            "SELECT id, result_json FROM main_seeds.domain_analysis_results "
            "WHERE analysis_type='join_cardinality' "
            "  AND status='success' "
            "  AND (superseded_by IS NULL OR superseded_by='') "
            "  AND list_contains("
            "       list_transform(string_split(LOWER(source_tables), ','),"
            "                      x -> trim(x)), LOWER(?)) "
            "  AND list_contains("
            "       list_transform(string_split(LOWER(source_tables), ','),"
            "                      x -> trim(x)), LOWER(?))",
            [pair_lex[0], pair_lex[1]],
        ).fetchall()
    except duckdb.Error:
        return []


def lookup_cardinality_dar(t1: str, t2: str,
                           keys: list[tuple[str, str]],
                           conn) -> Optional[dict]:
    """Find the direct cardinality DAR matching the pair on the given
    keys. Returns the parsed result_json (with `_dar_id` injected) or
    None when no direct DAR matches.

    Bridge DARs are not returned by this function — bridges are
    suggestions for the recommended-bridge alternative, not the DAR
    that gates the join the LLM actually wrote.
    """
    pair_lex = sorted([t1.lower(), t2.lower()])
    if t1.lower() == pair_lex[0]:
        keys_t1 = [k[0].upper() for k in keys]
        keys_t2 = [k[1].upper() for k in keys]
    else:
        keys_t1 = [k[1].upper() for k in keys]
        keys_t2 = [k[0].upper() for k in keys]

    for dar_id, rj in _query_pair_dars(conn, t1, t2):
        try:
            f = json.loads(rj or "{}")
        except (json.JSONDecodeError, TypeError):
            continue
        if f.get("kind") != "direct":
            continue
        f_keys_t1 = [c.upper() for c in (f.get("key_columns_t1") or [])]
        f_keys_t2 = [c.upper() for c in (f.get("key_columns_t2") or [])]
        if (sorted(f_keys_t1) == sorted(keys_t1)
                and sorted(f_keys_t2) == sorted(keys_t2)):
            f["_dar_id"] = dar_id
            return f
    return None


def find_recommended_bridge(t1: str, t2: str, conn) -> Optional[dict]:
    """For a pair where direct is catastrophic, find the highest-quality
    per_record_key bridge DAR to suggest as the recommended fix.
    Returns the parsed DAR or None when no bridge available.
    """
    bridges: list[dict] = []
    for dar_id, rj in _query_pair_dars(conn, t1, t2):
        try:
            f = json.loads(rj or "{}")
        except Exception:  # noqa: BLE001
            continue
        if (f.get("kind") == "bridge"
                and f.get("fanout_class") == "per_record_key"):
            f["_dar_id"] = dar_id
            bridges.append(f)
    if not bridges:
        return None
    bridges.sort(key=lambda b: -float(b.get("matched_keys_ratio") or 0))
    return bridges[0]


# ─── Lazy on-demand analysis (closes #92) ─────────────────────────────

def _refresh_dar_table_from_csv(conn) -> bool:
    """Reload `main_seeds.domain_analysis_results` from the seed CSV so
    that DARs the analyzer just appended are visible to subsequent
    lookups in the same connection. Best-effort; returns True on success.
    """
    if not _DAR_CSV.exists():
        return False
    try:
        conn.execute(
            "CREATE OR REPLACE TABLE main_seeds.domain_analysis_results "
            "AS SELECT * FROM read_csv_auto(?, sample_size=-1)",
            [str(_DAR_CSV)],
        )
        return True
    except duckdb.Error:
        return False


def trigger_lazy_analysis(t1: str, t2: str, conn) -> bool:
    """Closes known_issue #92. Invoke
    `run_join_cardinality_analysis.analyze_pair` programmatically for
    a single pair, then refresh the conn's cached table from CSV so the
    new DARs are visible to subsequent lookups.

    Returns True when at least one DAR was emitted AND the refresh
    succeeded; False on any failure (keeps F.3 best-effort — a missed
    lazy analysis just means the join passes through validation).
    """
    try:
        from run_join_cardinality_analysis import (
            analyze_pair, _source_tables,
        )
    except ImportError:
        return False
    try:
        all_tables = _source_tables(conn)
        n = analyze_pair(conn, t1.lower(), t2.lower(),
                         all_tables=all_tables)
    except Exception:  # noqa: BLE001
        return False
    if n <= 0:
        return False
    return _refresh_dar_table_from_csv(conn)


# ─── Retry hint formatting ───────────────────────────────────────────

def format_retry_hint(rejection: dict) -> str:
    """Build LLM-readable hint for the existing retry harness
    (`Business_Glossary.py` Step d). Mirrors the catastrophic-join
    pattern with a recommended-bridge suggestion when available.
    """
    pair = rejection.get("pair", ("?", "?"))
    bad_keys = rejection.get("catastrophic_keys") or []
    dar_id = rejection.get("catastrophic_dar_id", "?")
    avg = rejection.get("catastrophic_avg_fanout", "?")
    bridge = rejection.get("recommended_bridge")

    keys_left = ",".join(k[0] for k in bad_keys) or "?"
    keys_right = ",".join(k[1] for k in bad_keys) or "?"
    parts = [
        "The generated SQL contains a join classified as "
        "catastrophic_fanout per cardinality evidence:",
        "",
        f"  {pair[0]}.{keys_left} = {pair[1]}.{keys_right}  ->  "
        f"catastrophic_fanout ({dar_id}, avg fanout {avg}x)",
    ]
    if bridge:
        bridge_via = bridge.get("bridge_via", "?")
        bl = "+".join(bridge.get("bridge_keys_left") or []) or "?"
        br = "+".join(bridge.get("bridge_keys_right") or []) or "?"
        k1 = "+".join(bridge.get("key_columns_t1") or []) or "?"
        k2 = "+".join(bridge.get("key_columns_t2") or []) or "?"
        parts += [
            "",
            "Use the per_record_key bridge instead:",
            "",
            f"  Bridge via {bridge_via}: {pair[0]}.{k1} = "
            f"{bridge_via}.{bl}  ::  {bridge_via}.{br} = {pair[1]}.{k2}",
            "",
            f"Reference: {bridge.get('_dar_id')}",
        ]
    else:
        parts += [
            "",
            "No per_record_key bridge currently exists for this pair "
            "in cardinality evidence. Consider revising the term's "
            "grain or adding bridge tables to scope.",
        ]
    return "\n".join(parts)


# ─── Main entry ───────────────────────────────────────────────────────

def validate_s2t_sql(sql: str, scope_tables: list[str],
                     conn) -> dict:
    """F.3 main entry. Parse SQL, validate joins against cardinality
    evidence.

    Returns:
        {"status": "passed"} when no joins are catastrophic, OR
        {"status": "rejected_catastrophic_join",
         "pair": (t1, t2),
         "catastrophic_keys": [(l_col, r_col), ...],
         "catastrophic_dar_id": "DAR-NNNNN",
         "catastrophic_avg_fanout": float,
         "recommended_bridge": {parsed DAR JSON} | None,
         "hint": "<formatted retry hint for LLM>"}

    The "passed" status with `reason` field is also returned for benign
    skip cases (empty SQL, parse failure, no scope, etc.).
    """
    if not sql or not sql.strip():
        return {"status": "passed", "reason": "empty_sql_skipped"}

    scope_set = {t.lower() for t in (scope_tables or [])}
    joins = extract_joins_from_sql(sql)
    if not joins:
        return {"status": "passed", "reason": "no_joins_extracted"}

    for j in joins:
        lt = j["left_table"]
        rt = j["right_table"]
        keys = j["join_keys"]

        if scope_set and (lt not in scope_set or rt not in scope_set):
            continue
        if lt == rt:
            continue

        dar = lookup_cardinality_dar(lt, rt, keys, conn)
        if dar is None:
            # Lazy analysis — closes #92.
            if trigger_lazy_analysis(lt, rt, conn):
                dar = lookup_cardinality_dar(lt, rt, keys, conn)
            if dar is None:
                continue  # no evidence -> pass through

        if (dar.get("fanout_class") == "catastrophic_fanout"
                and not dar.get("safe_direction")):
            # Direction-aware: a pair whose evidence records a safe
            # N:1 lookup direction is not auto-rejected — the grain /
            # semantic gate at deploy remains the backstop for SQL
            # that joins in the exploding direction.
            recommended = find_recommended_bridge(lt, rt, conn)
            rejection = {
                "status": "rejected_catastrophic_join",
                "pair": (lt, rt),
                "catastrophic_keys": keys,
                "catastrophic_dar_id": dar.get("_dar_id"),
                "catastrophic_avg_fanout": dar.get("avg_fanout"),
                "recommended_bridge": recommended,
            }
            rejection["hint"] = format_retry_hint(rejection)
            return rejection

    return {"status": "passed"}
